Revert "`torch.bcomplex32` shell dtype. (#173783)"
This reverts commit 7ecfdc5f885ab997a050d8c051784e997f69bd18.

Reverted https://github.com/pytorch/pytorch/pull/173783 on behalf of https://github.com/yangw-dev due to sorry internal test error: .cpp:59:51: error: no member named 'BComplex32', please contact a internal meta folks to resolve this ([comment](https://github.com/pytorch/pytorch/pull/173783#issuecomment-4090690450))