Revert "Disable TD for the cpython tests (#178185)"
This reverts commit e553e28525dc8f2fcefd05230c197589a8a36a65.

Reverted https://github.com/pytorch/pytorch/pull/178185 on behalf of https://github.com/georgehong due to Revert this stack due to observing first-time test breakages: FAILED CONSISTENTLY: test/test_multiprocessing_spawn.py::ParallelForkServerShouldWorkTest::test_terminate_signal -- torch._dynamo.exc.InternalTorchDynamoError: AttributeError: 'method' object has no attribute '__dict__' ([comment](https://github.com/pytorch/pytorch/pull/176773#issuecomment-4128280508))