Revert "Remove TorchVitals (#178479)"
This reverts commit f62958ff29ec4cf0220e369ea34e1ccb15fd030b.

Reverted https://github.com/pytorch/pytorch/pull/178479 on behalf of https://github.com/georgehong due to change is breaking internal tests: AttributeError: module 'torch' has no attribute 'set_vital' ([comment](https://github.com/pytorch/pytorch/pull/178479#issuecomment-4145885127))