test: fix only 0-dimensional arrays can be converted to Python scalars (#181144)
I got the following error when running `TestFakeQuantize.test_fq_module_per_channel`:
```
File "/third_party/py/torch/testing/_internal/hypothesis_utils.py", line 245, in per_channel_tensor
    axis = int(np.random.randint(0, X.ndim, 1))
TypeError: only 0-dimensional arrays can be converted to Python scalars
```
The issue was caused by calling `int()` on a 1D NumPy array with a single element, which is returned by `np.random.randint(low, high, 1)`. In recent versions of NumPy, this conversion is restricted or fails if the array is not 0-dimensional.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/181144
Approved by: https://github.com/albanD