Revert "Implement MKLGenerator  (#151218)"
This reverts commit 8f44b8f091dadcaab6e1a959e2bf2a1f31d1bc15.

Reverted https://github.com/pytorch/pytorch/pull/151218 on behalf of https://github.com/yangw-dev due to sorry, it breaks internal test. error:fbcode/caffe2/aten/src/ATen/CPUGeneratorImpl.cpp:8:10: fatal error: 'ATen/mklrng/MKLGeneratorImpl.h' file not found ([comment](https://github.com/pytorch/pytorch/pull/151218#issuecomment-3761997088))