[backend] bug fix: fix error: ‘mul_and_reduce_shoup_avx512_full’ is not a member of ‘fhe
(cherry picked from commit cab97b89c4e9c832516f50e8415a317584c29af6)