[aotautograd] Fix inplace checks in autograd backward functions during functionalization (#177213)
During `_functionalized_f_helper`, we call `before.copy_(after)`. If the compiled function is a custom autograd function with an inplace op during the backward, this can trigger [inplace correctness check](https://docs.pytorch.org/docs/stable/autograd.html#in-place-correctness-checks) unintentionally. This causes an exception
```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
```

This PR instead wraps the `before.copy_(after)` with a `torch.no_grad()` context to avoid the inplace check.

Example script:
```
import torch

class MutateBufferInBackward(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, buf):
        ctx.save_for_backward(buf)
        return x * buf.mean()

    @staticmethod
    def backward(ctx, grad_output):
        (buf,) = ctx.saved_tensors
        buf.mul_(2.0)
        return grad_output * buf.mean(), None

@torch.compile
def f(x, buf):
    return MutateBufferInBackward.apply(x, buf)

def main():
    device = "cuda"
    x = torch.randn(16, device=device, requires_grad=True)
    buf = torch.randn(16, device=device, requires_grad=True)

    out = f(x, buf)
    out.sum().backward()
    print("Success!")

if __name__ == "__main__":
    main()
    ```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/177213
Approved by: https://github.com/aorenste, https://github.com/frgossen