Revert "dist: add list_keys to Store API (#167883)"
This reverts commit a5f62f3702fecc8a04d78e1a2a1e0ada5659b3e8.

Reverted https://github.com/pytorch/pytorch/pull/167883 on behalf of https://github.com/yangw-dev due to break some internal test,  error: use of undeclared identifier, reached out author but no resp, so revert this to keep diff train hygiene ([comment](https://github.com/pytorch/pytorch/pull/167883#issuecomment-3555212038))