Workaround for nvrtcCompileProgram changing locale in CUDA < 12.6.2 (#180569)
There is a bug in CUDA 11.7 until CUDA 12.6.2 which changes the current thread locale when calling nvrtcCompileProgram.
See e.g. https://stackoverflow.com/questions/74044994 This also includes the encoding used by Python by default for e.g. subsequent invocations of `subprocess` calls. When the user environment is now set to e.g. UTF-8 and changed by CUDA (to ASCII/ANSI_X3.4-1968) Python will fail to decode UTF-8 output from programs invoked.
This happens e.g. in `test_torch` which calls `from scipy import stats` which runs `lscpu` and errors with something like
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 96: ordinal not in range(128)

Fix by wrapping the nvrtcCompileProgram saving and restoring the thread locale.

See previous PR #121822
Pull Request resolved: https://github.com/pytorch/pytorch/pull/180569
Approved by: https://github.com/Skylion007