[Test][elastic]fix test_etcd_server_with_rendezvous (#165431)
Fixes [#2124](https://github.com/intel/torch-xpu-ops/issues/2124)

This PR fixes the following error observed while running the unit test:

`python -m unittest etcd_server_test.EtcdServerTest.test_etcd_server_with_rendezvous
`
Error log:
```
======================================================================
ERROR: test_etcd_server_with_rendezvous (etcd_server_test.EtcdServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sdp/xiangdong/pytorch/test/distributed/elastic/rendezvous/etcd_server_test.py", line 58, in test_etcd_server_with_rendezvous
    rdzv_handler = EtcdRendezvousHandler(rdzv)
TypeError: EtcdRendezvousHandler.__init__() missing 1 required positional argument: 'local_addr'
----------------------------------------------------------------------
Ran 1 test in 1.016s
FAILED (errors=1)
```
Root cause:
The test case instantiates `EtcdRendezvousHandler `without providing the required `local_addr `argument, leading to a `TypeError`.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/165431
Approved by: https://github.com/EikanWang, https://github.com/guangyey, https://github.com/d4l3k