Don't create CPU FlexAttention tests if CPU doesn't support it (#174881)
Multiple tests (e.g. `TestFlexAttentionCPU::test_GQA_score_mod0_cpu_float32`) fail with
> torch._inductor.exc.InductorError: LoweringException: NotImplementedError: torch.compile on current platform is not supported for CPU.

This happens when CUDA support is available but the CPU doesn't support FlexAttention (e.g. missing AVX2). E.g. Grace Hopper platforms.

Also reduce duplication in the `*_SUPPORTED` and `TEST_ON_*` constants.

Followup to https://github.com/pytorch/pytorch/pull/170886 by @xwang233

The main change is that CPU tests won't be instantiated automatically when CUDA tests are instantiated.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/174881
Approved by: https://github.com/malfet, https://github.com/drisspg